import type { Bike, ChallengeDefinition } from './types';
export const MAX_RIDE_SPEED = 140 / 3.6;
export const BIKES: Bike[] = [
  {
    id: '125',
    name: 'Töffli',
    tag: 'ALLTAGSFAHRER',
    price: 0,
    level: 1,
    acceleration: 0.19,
    handling: 13,
    stability: 1,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#e7e7df',
  },
  {
    id: 'scooter',
    name: 'Roller',
    tag: 'KLEINE RÄDER. GROSSE STADT.',
    price: 250,
    level: 2,
    acceleration: 0.215,
    handling: 14,
    stability: 1.06,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#627dac',
  },
  {
    id: '450',
    name: 'Supermoto',
    tag: 'FÜR DIE STRASSE',
    price: 450,
    level: 3,
    acceleration: 0.24,
    handling: 15,
    stability: 0.93,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#dc632e',
  },
  {
    id: '701',
    name: 'Sport',
    tag: 'KEINE HALBEN SACHEN',
    price: 1000,
    level: 6,
    acceleration: 0.28,
    handling: 13.8,
    stability: 1.18,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#d9f365',
  },
];
export const LEVELS = [0, 200, 550, 1050, 1750, 2650, 3750, 5100, 6750, 8750];
export const LEVEL_NAMES = [
  'NEU DABEI',
  'STAMMFAHRER',
  'SUMO-STUFE',
  'NACHTSCHICHT',
  'LINIENFINDER',
  'EINZYLINDER',
  'SPÄTSCHICHT',
  'STRASSENPROFI',
  'PFUSCH-CREW',
  'STRASSENLEGENDE',
];
export const DAILY_CHALLENGES: ChallengeDefinition[] = [
  {
    id: 'three-rides',
    title: 'Zurück aufs Bike',
    description: '3 Fahrten beenden',
    stat: 'runs',
    target: 3,
    xp: 120,
    coins: 90,
    cadence: 'daily',
  },
  {
    id: 'one-wheel',
    title: 'Vorderrad optional',
    description: '250 m Wheelie fahren',
    stat: 'wheelie',
    target: 250,
    xp: 150,
    coins: 100,
    cadence: 'daily',
  },
  {
    id: 'close-call',
    title: 'Knapp vorbei',
    description: '5 knappe Manöver schaffen',
    stat: 'nearMisses',
    target: 5,
    xp: 170,
    coins: 120,
    cadence: 'daily',
  },
  {
    id: 'night-shift',
    title: 'Kilometer machen',
    description: '2.000 m fahren',
    stat: 'distance',
    target: 2000,
    xp: 100,
    coins: 80,
    cadence: 'daily',
  },
];
export const WEEKLY_CHALLENGES: ChallengeDefinition[] = [
  {
    id: 'weekly-distance',
    title: 'Deine Woche',
    description: 'Diese Woche 20 km fahren',
    stat: 'distance',
    target: 20000,
    xp: 800,
    coins: 500,
    cadence: 'weekly',
  },
];
export const PAINTS = [
  { name: 'Hell', value: '#e7e7df', price: 0 },
  { name: 'Asphalt', value: '#323638', price: 80 },
  { name: 'Signal', value: '#d9f365', price: 120 },
  { name: 'Orange', value: '#dc632e', price: 120 },
  { name: 'Kobalt', value: '#627dac', price: 120 },
  { name: 'Rennrot', value: '#b83232', price: 120 },
  { name: 'Eisblau', value: '#8ab9cf', price: 120 },
  { name: 'Tanne', value: '#3e5c52', price: 120 },
  { name: 'Sand', value: '#b6a083', price: 120 },
  { name: 'Violett', value: '#7461a5', price: 120 },
];
export const RIMS = [
  { name: 'Silber', value: '#a6acb0', price: 0 },
  { name: 'Schwarz', value: '#24282b', price: 60 },
  { name: 'Signal', value: '#d9f365', price: 100 },
  { name: 'Bronze', value: '#967847', price: 100 },
  { name: 'Kobalt', value: '#627dac', price: 100 },
];
export const REWARDS = [
  {
    id: 'starter-coins',
    title: 'STARTBONUS',
    description: '100 PFUSCH Coins. Einmalig.',
    kind: 'coins',
    level: 1,
  },
  {
    id: 'exclusive-rims',
    title: 'NACHT-FELGEN',
    description: 'Signal-Felgen für deine Fahrten.',
    kind: 'cosmetic',
    level: 5,
  },
  {
    id: 'early-drop',
    title: 'FRÜHZUGANG',
    description: 'Späterer Shop-Vorteil. Nur Vorschau.',
    kind: 'future',
    level: 1,
  },
  {
    id: 'shipping',
    title: 'Kostenloser Versand',
    description: 'Späterer Shop-Vorteil. Nur Vorschau.',
    kind: 'future',
    level: 1,
  },
  {
    id: 'chf-five',
    title: 'CHF 5 Belohnung',
    description: 'Späterer Shop-Vorteil. Nur Vorschau.',
    kind: 'future',
    level: 1,
  },
] as const;
