import type { Bike, ChallengeDefinition } from './types';
export const MAX_RIDE_SPEED = 140 / 3.6;
export const BIKES: Bike[] = [
  {
    id: '125',
    name: 'Töffli',
    tag: 'THE DAILY DRIVER',
    price: 0,
    level: 1,
    acceleration: 0.19,
    handling: 13,
    stability: 1,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#e7e7df',
  },
  {
    id: 'scooter',
    name: 'Roller',
    tag: 'SMALL WHEELS. BIG CITY.',
    price: 250,
    level: 2,
    acceleration: 0.215,
    handling: 14,
    stability: 1.06,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#627dac',
  },
  {
    id: '450',
    name: 'Supermoto',
    tag: 'MADE FOR THE STREETS',
    price: 450,
    level: 3,
    acceleration: 0.24,
    handling: 15,
    stability: 0.93,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#dc632e',
  },
  {
    id: '701',
    name: 'Sport',
    tag: 'NO HALF MEASURES',
    price: 1000,
    level: 6,
    acceleration: 0.28,
    handling: 13.8,
    stability: 1.18,
    maxSpeed: MAX_RIDE_SPEED,
    color: '#d9f365',
  },
];
export const LEVELS = [0, 200, 550, 1050, 1750, 2650, 3750, 5100, 6750, 8750];
export const LEVEL_NAMES = [
  'NEW BLOOD',
  'STREET REGULAR',
  'SUMO LICENSE',
  'AFTER HOURS',
  'LINE FINDER',
  'BIG SINGLE',
  'NIGHT SHIFT',
  'STREET AUTHORITY',
  'PFUSCH CREW',
  'STREET LEGEND',
];
export const DAILY_CHALLENGES: ChallengeDefinition[] = [
  {
    id: 'three-rides',
    title: 'Back on the bike',
    description: 'Finish 3 rides',
    stat: 'runs',
    target: 3,
    xp: 120,
    coins: 90,
    cadence: 'daily',
  },
  {
    id: 'one-wheel',
    title: 'Front wheel optional',
    description: 'Wheelie for 250 m',
    stat: 'wheelie',
    target: 250,
    xp: 150,
    coins: 100,
    cadence: 'daily',
  },
  {
    id: 'close-call',
    title: 'Thread the needle',
    description: 'Make 5 near misses',
    stat: 'nearMisses',
    target: 5,
    xp: 170,
    coins: 120,
    cadence: 'daily',
  },
  {
    id: 'night-shift',
    title: 'Put in the distance',
    description: 'Ride 2,000 m',
    stat: 'distance',
    target: 2000,
    xp: 100,
    coins: 80,
    cadence: 'daily',
  },
];
export const WEEKLY_CHALLENGES: ChallengeDefinition[] = [
  {
    id: 'weekly-distance',
    title: 'Own the streets',
    description: 'Ride 20 km this week',
    stat: 'distance',
    target: 20000,
    xp: 800,
    coins: 500,
    cadence: 'weekly',
  },
];
export const PAINTS = [
  { name: 'Chalk', value: '#e7e7df', price: 0 },
  { name: 'Asphalt', value: '#323638', price: 80 },
  { name: 'Signal', value: '#d9f365', price: 120 },
  { name: 'Burnt orange', value: '#dc632e', price: 120 },
  { name: 'Cobalt', value: '#627dac', price: 120 },
  { name: 'Racing red', value: '#b83232', price: 120 },
  { name: 'Ice blue', value: '#8ab9cf', price: 120 },
  { name: 'Pine', value: '#3e5c52', price: 120 },
  { name: 'Sand', value: '#b6a083', price: 120 },
  { name: 'Violet', value: '#7461a5', price: 120 },
];
export const RIMS = [
  { name: 'Silver', value: '#a6acb0', price: 0 },
  { name: 'Black', value: '#24282b', price: 60 },
  { name: 'Signal', value: '#d9f365', price: 100 },
  { name: 'Bronze', value: '#967847', price: 100 },
  { name: 'Cobalt', value: '#627dac', price: 100 },
];
export const REWARDS = [
  {
    id: 'starter-coins',
    title: 'Crew allowance',
    description: '100 PFUSCH Coins. One time, on the house.',
    kind: 'coins',
    level: 1,
  },
  {
    id: 'exclusive-rims',
    title: 'After hours rims',
    description: 'Unlock signal rims for your night rides.',
    kind: 'cosmetic',
    level: 5,
  },
  {
    id: 'early-drop',
    title: 'Early drop access',
    description: 'Future shop benefit. Preview only.',
    kind: 'future',
    level: 1,
  },
  {
    id: 'shipping',
    title: 'Free shipping',
    description: 'Future shop benefit. Preview only.',
    kind: 'future',
    level: 1,
  },
  {
    id: 'chf-five',
    title: 'CHF 5 reward',
    description: 'Future shop benefit. Preview only.',
    kind: 'future',
    level: 1,
  },
] as const;
